name: CD Pipeline

on:
  push:
    branches: [ "main" ] # Hanya menyala kalau kode sudah masuk ke main

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest

    steps:
    - name: Tarik Kode dari Repository
      uses: actions/checkout@v4

    - name: Login ke Azure Container Registry (ACR)
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build dan Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.ACR_LOGIN_SERVER }}/qurban-mmi:latest

    - name: Deploy ke Azure App Service (Staging Slot)
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'qurban-mmi'
        slot-name: 'qurban-mmi-staging'
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
        images: '${{ secrets.ACR_LOGIN_SERVER }}/qurban-mmi:latest'