name: CI Pipeline

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Tarik Kode dari Repository
      uses: actions/checkout@v4

    - name: Setup Node.js v22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Generate Prisma Client (Wajib buat database)
      run: npx prisma generate

    - name: Pengecekan Standar Kode (Linter)
      run: npm run lint

    - name: Jalankan Unit Test (Menunggu Orang 2)
      run: npm test -- --coverage